services:
  db:
    container_name: patching-risk-db
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nvd
      - MONGO_INITDB_ROOT_PASSWORD=nvd
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: